# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Dec  8 03:49:11 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ETMITM(object):
    def setupUi(self, ETMITM):
        ETMITM.setObjectName(_fromUtf8("ETMITM"))
        ETMITM.resize(879, 617)
        ETMITM.setWindowTitle(QtGui.QApplication.translate("ETMITM", "EMITM", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(ETMITM)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 191, 31))
        self.pushButton.setText(QtGui.QApplication.translate("ETMITM", "Install prerequisites", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 550, 171, 31))
        self.pushButton_2.setText(QtGui.QApplication.translate("ETMITM", "Close this window", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 90, 113, 27))
        self.lineEdit.setWhatsThis(_fromUtf8(""))
        self.lineEdit.setText(QtGui.QApplication.translate("ETMITM", "wlan1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setText(QtGui.QApplication.translate("ETMITM", "Interfces", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 281, 21))
        self.label_2.setText(QtGui.QApplication.translate("ETMITM", "Broadcast fake access point on:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 130, 113, 27))
        self.lineEdit_2.setWhatsThis(_fromUtf8(""))
        self.lineEdit_2.setText(QtGui.QApplication.translate("ETMITM", "wlan0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 231, 21))
        self.label_3.setText(QtGui.QApplication.translate("ETMITM", "Internet source interface:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(300, 170, 151, 27))
        self.lineEdit_3.setWhatsThis(_fromUtf8(""))
        self.lineEdit_3.setText(QtGui.QApplication.translate("ETMITM", "default network", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 281, 21))
        self.label_4.setText(QtGui.QApplication.translate("ETMITM", "Essid for fake network to make:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 10, 221, 31))
        self.pushButton_3.setText(QtGui.QApplication.translate("ETMITM", "Check For Prerequisites", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 210, 110, 31))
        self.pushButton_4.setText(QtGui.QApplication.translate("ETMITM", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("ETMITM", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 50, 201, 21))
        self.label_7.setText(QtGui.QApplication.translate("ETMITM", "domain-name-servers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(680, 50, 161, 27))
        self.lineEdit_4.setText(QtGui.QApplication.translate("ETMITM", "192.168.179.1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(680, 90, 161, 27))
        self.lineEdit_5.setText(QtGui.QApplication.translate("ETMITM", "192.168.179.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(470, 90, 201, 21))
        self.label_8.setText(QtGui.QApplication.translate("ETMITM", "subnet:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(680, 130, 161, 27))
        self.lineEdit_6.setText(QtGui.QApplication.translate("ETMITM", "255.255.255.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(470, 130, 201, 21))
        self.label_9.setText(QtGui.QApplication.translate("ETMITM", "netmsk:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(530, 170, 151, 27))
        self.lineEdit_7.setText(QtGui.QApplication.translate("ETMITM", "192.168.179.10", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(470, 170, 61, 21))
        self.label_10.setText(QtGui.QApplication.translate("ETMITM", "range:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_8 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(680, 210, 161, 27))
        self.lineEdit_8.setText(QtGui.QApplication.translate("ETMITM", "192.168.179.1", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(470, 210, 201, 21))
        self.label_11.setText(QtGui.QApplication.translate("ETMITM", "routers:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_9 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(710, 170, 161, 27))
        self.lineEdit_9.setText(QtGui.QApplication.translate("ETMITM", "192.168.179.100", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(690, 170, 16, 21))
        self.label_12.setText(QtGui.QApplication.translate("ETMITM", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(340, 550, 110, 31))
        self.pushButton_5.setText(QtGui.QApplication.translate("ETMITM", "Close Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(199, 550, 131, 31))
        self.pushButton_6.setText(QtGui.QApplication.translate("ETMITM", "Clean System", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(640, 550, 231, 31))
        self.pushButton_7.setText(QtGui.QApplication.translate("ETMITM", "Shut Down ALL THINGS!", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 260, 851, 281))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 851, 251))
        self.textBrowser.setHtml(QtGui.QApplication.translate("ETMITM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Main Log</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 851, 251))
        self.textBrowser_2.setHtml(QtGui.QApplication.translate("ETMITM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ettercup Log</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        ETMITM.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ETMITM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        ETMITM.setMenuBar(self.menubar)

        self.retranslateUi(ETMITM)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), ETMITM.close)
        QtCore.QObject.connect(self.pushButton_7, QtCore.SIGNAL(_fromUtf8("clicked()")), ETMITM.close)
        QtCore.QMetaObject.connectSlotsByName(ETMITM)

    def retranslateUi(self, ETMITM):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ETMITM", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("ETMITM", "Tab 2", None, QtGui.QApplication.UnicodeUTF8))

